import type { WorkoutProgram, WorkoutDay } from "./types"

const restDay = (id: string, label: string, dayOfWeek: number): WorkoutDay => ({
  id,
  label,
  dayOfWeek,
  type: "Rest",
  isRest: true,
  exercises: [],
  cardio: {
    name: "",
    duration: 0,
    instructions: [],
    tips: [],
  },
})

const monday: WorkoutDay = {
  id: "3day-monday",
  label: "Monday",
  dayOfWeek: 1,
  type: "Full Body A",
  isRest: false,
  cardio: {
    name: "Treadmill LISS",
    duration: 25,
    instructions: [
      "Set the treadmill to a comfortable walking or light jogging pace.",
      "Maintain a steady, conversational pace for the full 25 minutes.",
      "Keep your posture upright and arms relaxed at your sides.",
    ],
    tips: [
      "You should be able to hold a conversation — if you can't, slow down.",
      "Aim for a heart rate of roughly 50–65% of your maximum.",
    ],
  },
  exercises: [
    {
      id: "3day-monday-goblet-squat",
      name: "Goblet Squat",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Legs",
      instructions: [
        "Hold a dumbbell vertically at your chest with both hands, elbows pointing down.",
        "Stand with feet shoulder-width apart, toes slightly turned out.",
        "Squat down until your thighs are parallel to the floor, keeping your chest up, then drive through your heels to stand.",
      ],
      tips: [
        "Keep your knees tracking over your toes throughout the movement.",
        "Think 'chest up, hips back' to maintain a neutral spine.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=goblet+squat+form+tutorial",
    },
    {
      id: "3day-monday-romanian-deadlift",
      name: "Romanian Deadlift",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Hamstrings",
      instructions: [
        "Stand holding dumbbells in front of your thighs, feet hip-width apart.",
        "Hinge at the hips, lowering the weights along your legs while keeping a slight bend in your knees.",
        "Lower until you feel a stretch in your hamstrings, then drive your hips forward to return to standing.",
      ],
      tips: [
        "Keep the dumbbells close to your legs the entire time.",
        "Avoid rounding your lower back — think 'proud chest' as you hinge.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=romanian+deadlift+form+tutorial",
    },
    {
      id: "3day-monday-dumbbell-bench-press",
      name: "Dumbbell Bench Press",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Chest",
      instructions: [
        "Lie on a flat bench holding a dumbbell in each hand at chest level, elbows at roughly 45 degrees.",
        "Press the dumbbells up until your arms are nearly straight, then lower slowly back to the start.",
        "Keep your feet flat on the floor and maintain a slight arch in your lower back.",
      ],
      tips: [
        "Lower the weights with control — the eccentric (lowering) phase builds strength too.",
        "Avoid flaring your elbows out to 90 degrees; a slight tuck protects your shoulders.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=dumbbell+bench+press+form+tutorial",
    },
    {
      id: "3day-monday-bent-over-row",
      name: "Bent-Over Row",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Back",
      instructions: [
        "Hold dumbbells with a neutral grip, hinge forward at the hips until your torso is roughly parallel to the floor.",
        "Pull the dumbbells toward your hips, leading with your elbows and squeezing your shoulder blades together at the top.",
        "Lower the weights slowly and repeat.",
      ],
      tips: [
        "Keep your core braced to protect your lower back.",
        "Think 'elbows to your back pockets' to engage your lats properly.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=bent+over+row+form+tutorial",
    },
    {
      id: "3day-monday-shoulder-press",
      name: "Shoulder Press",
      sets: 3,
      reps: "10",
      restSeconds: 60,
      muscleGroup: "Shoulders",
      instructions: [
        "Sit or stand holding dumbbells at shoulder height, palms facing forward.",
        "Press the dumbbells straight overhead until your arms are fully extended.",
        "Lower slowly back to shoulder height and repeat.",
      ],
      tips: [
        "Avoid leaning back as you press — engage your core to stay upright.",
        "Don't lock out your elbows aggressively at the top; keep a soft bend.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=dumbbell+shoulder+press+form+tutorial",
    },
    {
      id: "3day-monday-bicep-curl",
      name: "Bicep Curl",
      sets: 3,
      reps: "12",
      restSeconds: 45,
      muscleGroup: "Biceps",
      instructions: [
        "Stand holding dumbbells at your sides, palms facing forward.",
        "Curl the weights up toward your shoulders, keeping your elbows tucked in at your sides.",
        "Lower slowly back to the starting position.",
      ],
      tips: [
        "Avoid swinging your body — the movement should come from your arms only.",
        "Squeeze your biceps at the top of each rep for a better contraction.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=bicep+curl+form+tutorial",
    },
    {
      id: "3day-monday-tricep-overhead-extension",
      name: "Tricep Overhead Extension",
      sets: 3,
      reps: "12",
      restSeconds: 45,
      muscleGroup: "Triceps",
      instructions: [
        "Hold one dumbbell with both hands overhead, arms extended.",
        "Bend your elbows to lower the dumbbell behind your head, keeping your upper arms still.",
        "Extend your arms back to the start position.",
      ],
      tips: [
        "Keep your elbows pointing forward — don't let them flare out to the sides.",
        "Move slowly on the way down to feel a full tricep stretch.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=tricep+overhead+extension+form+tutorial",
    },
    {
      id: "3day-monday-plank",
      name: "Plank",
      sets: 3,
      reps: "30 sec",
      restSeconds: 45,
      muscleGroup: "Core",
      instructions: [
        "Start in a forearm plank position with your elbows under your shoulders and feet hip-width apart.",
        "Keep your body in a straight line from head to heels — don't let your hips sag or rise.",
        "Hold for 30 seconds, breathing steadily.",
      ],
      tips: [
        "Squeeze your glutes and brace your abs as if you're about to be punched.",
        "If 30 seconds is too easy, add time; if too hard, drop to your knees.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=plank+form+tutorial",
    },
  ],
}

const wednesday: WorkoutDay = {
  id: "3day-wednesday",
  label: "Wednesday",
  dayOfWeek: 3,
  type: "Full Body B",
  isRest: false,
  cardio: {
    name: "Treadmill LISS",
    duration: 25,
    instructions: [
      "Set the treadmill to a comfortable walking or light jogging pace.",
      "Maintain a steady, conversational pace for the full 25 minutes.",
      "Keep your posture upright and arms relaxed at your sides.",
    ],
    tips: [
      "You should be able to hold a conversation — if you can't, slow down.",
      "Aim for a heart rate of roughly 50–65% of your maximum.",
    ],
  },
  exercises: [
    {
      id: "3day-wednesday-sumo-squat",
      name: "Sumo Squat",
      sets: 3,
      reps: "15",
      restSeconds: 60,
      muscleGroup: "Legs",
      instructions: [
        "Stand with feet wider than shoulder-width and toes pointed out at 45 degrees, holding a dumbbell at your chest.",
        "Squat down until your thighs are parallel to the floor, keeping your knees tracking over your toes.",
        "Drive through your heels to return to standing.",
      ],
      tips: [
        "A wider stance targets your inner thighs more than a standard squat.",
        "Keep your chest up and avoid letting your knees cave inward.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=sumo+squat+form+tutorial",
    },
    {
      id: "3day-wednesday-dumbbell-deadlift",
      name: "Dumbbell Deadlift",
      sets: 3,
      reps: "10",
      restSeconds: 60,
      muscleGroup: "Hamstrings",
      instructions: [
        "Stand with feet hip-width apart, holding dumbbells in front of your thighs.",
        "Hinge at the hips and bend your knees to lower the dumbbells toward the floor, keeping your back flat.",
        "Drive through your heels and extend your hips to return to standing.",
      ],
      tips: [
        "Keep the dumbbells close to your body throughout the movement.",
        "Think about pushing the floor away rather than pulling the weight up.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=dumbbell+deadlift+form+tutorial",
    },
    {
      id: "3day-wednesday-incline-dumbbell-press",
      name: "Incline Dumbbell Press",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Chest",
      instructions: [
        "Set a bench to a 30–45 degree incline and lie back holding dumbbells at chest height.",
        "Press the weights up and slightly together until your arms are nearly straight.",
        "Lower slowly back to chest level and repeat.",
      ],
      tips: [
        "The incline angle shifts emphasis to your upper chest.",
        "Keep your shoulder blades retracted against the bench throughout.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=incline+dumbbell+press+form+tutorial",
    },
    {
      id: "3day-wednesday-single-arm-dumbbell-row",
      name: "Single-Arm Dumbbell Row",
      sets: 3,
      reps: "12 each",
      restSeconds: 60,
      muscleGroup: "Back",
      instructions: [
        "Place one hand and same-side knee on a bench for support, holding a dumbbell in the opposite hand.",
        "Pull the dumbbell up toward your hip, leading with your elbow and squeezing your shoulder blade at the top.",
        "Lower slowly and complete all reps before switching sides.",
      ],
      tips: [
        "Keep your back flat and parallel to the floor throughout.",
        "Avoid rotating your torso — the movement should be in your arm and shoulder blade only.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=single+arm+dumbbell+row+form+tutorial",
    },
    {
      id: "3day-wednesday-lateral-raises",
      name: "Lateral Raises",
      sets: 3,
      reps: "15",
      restSeconds: 45,
      muscleGroup: "Shoulders",
      instructions: [
        "Stand holding light dumbbells at your sides, palms facing in.",
        "With a slight bend in your elbows, raise your arms out to the sides until they reach shoulder height.",
        "Lower slowly back to the start.",
      ],
      tips: [
        "Use lighter weight than you think you need — this exercise is harder than it looks.",
        "Lead with your elbows, not your wrists, to keep tension on the deltoids.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=lateral+raises+form+tutorial",
    },
    {
      id: "3day-wednesday-hammer-curl",
      name: "Hammer Curl",
      sets: 3,
      reps: "12",
      restSeconds: 45,
      muscleGroup: "Biceps",
      instructions: [
        "Stand holding dumbbells at your sides with a neutral grip (palms facing each other).",
        "Curl the weights up toward your shoulders, keeping your elbows tucked in.",
        "Lower slowly back to the start.",
      ],
      tips: [
        "The neutral grip targets the brachialis and forearms in addition to the biceps.",
        "Keep the motion strict — no body swinging.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=hammer+curl+form+tutorial",
    },
    {
      id: "3day-wednesday-tricep-dips",
      name: "Tricep Dips",
      sets: 3,
      reps: "10",
      restSeconds: 45,
      muscleGroup: "Triceps",
      instructions: [
        "Sit on the edge of a bench or chair, hands gripping the edge beside your hips.",
        "Slide your hips off the edge and lower your body by bending your elbows to about 90 degrees.",
        "Press back up to the starting position.",
      ],
      tips: [
        "Keep your back close to the bench to isolate your triceps.",
        "For more difficulty, extend your legs straight out in front of you.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=tricep+dips+form+tutorial",
    },
    {
      id: "3day-wednesday-dead-bug",
      name: "Dead Bug",
      sets: 3,
      reps: "10",
      restSeconds: 45,
      muscleGroup: "Core",
      instructions: [
        "Lie on your back with arms extended toward the ceiling and knees bent at 90 degrees (tabletop position).",
        "Slowly lower your right arm overhead and extend your left leg toward the floor simultaneously, keeping your lower back pressed to the ground.",
        "Return to the start and repeat on the opposite side. That's one rep.",
      ],
      tips: [
        "Move slowly and with control — the goal is stability, not speed.",
        "If your lower back lifts off the floor, reduce the range of motion.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=dead+bug+exercise+form+tutorial",
    },
  ],
}

const friday: WorkoutDay = {
  id: "3day-friday",
  label: "Friday",
  dayOfWeek: 5,
  type: "Full Body C",
  isRest: false,
  cardio: {
    name: "Treadmill LISS",
    duration: 25,
    instructions: [
      "Set the treadmill to a comfortable walking or light jogging pace.",
      "Maintain a steady, conversational pace for the full 25 minutes.",
      "Keep your posture upright and arms relaxed at your sides.",
    ],
    tips: [
      "You should be able to hold a conversation — if you can't, slow down.",
      "Aim for a heart rate of roughly 50–65% of your maximum.",
    ],
  },
  exercises: [
    {
      id: "3day-friday-reverse-lunge",
      name: "Reverse Lunge",
      sets: 3,
      reps: "10 each",
      restSeconds: 60,
      muscleGroup: "Legs",
      instructions: [
        "Stand tall holding dumbbells at your sides.",
        "Step one foot back and lower your back knee toward the floor until both knees are at 90 degrees.",
        "Push through your front foot to return to standing, then repeat on the other leg.",
      ],
      tips: [
        "Stepping back (rather than forward) is easier on the knees and great for beginners.",
        "Keep your front shin vertical and your torso upright throughout.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=reverse+lunge+form+tutorial",
    },
    {
      id: "3day-friday-glute-bridge",
      name: "Glute Bridge",
      sets: 3,
      reps: "15",
      restSeconds: 60,
      muscleGroup: "Glutes",
      instructions: [
        "Lie on your back with knees bent and feet flat on the floor, hip-width apart.",
        "Drive through your heels to lift your hips off the floor until your body forms a straight line from shoulders to knees.",
        "Squeeze your glutes at the top, then lower slowly back down.",
      ],
      tips: [
        "Place a dumbbell across your hips for added resistance.",
        "Focus on squeezing your glutes — not just lifting your hips.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=glute+bridge+form+tutorial",
    },
    {
      id: "3day-friday-dumbbell-floor-press",
      name: "Dumbbell Floor Press",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Chest",
      instructions: [
        "Lie flat on the floor holding dumbbells at chest height, knees bent with feet flat.",
        "Press the dumbbells straight up until your arms are nearly extended.",
        "Lower slowly until your upper arms touch the floor, pause briefly, then press again.",
      ],
      tips: [
        "The floor acts as a natural range-of-motion limiter, making this joint-friendly.",
        "Keep your elbows at about 45 degrees from your body, not flared wide.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=dumbbell+floor+press+form+tutorial",
    },
    {
      id: "3day-friday-chest-supported-row",
      name: "Chest-Supported Row",
      sets: 3,
      reps: "12",
      restSeconds: 60,
      muscleGroup: "Back",
      instructions: [
        "Set a bench to a low incline (30–45 degrees) and lie face-down with a dumbbell in each hand.",
        "With your chest supported, row the dumbbells up toward your hips, squeezing your shoulder blades together.",
        "Lower with control and repeat.",
      ],
      tips: [
        "The supported position eliminates lower-back strain, letting you focus purely on your back.",
        "Drive your elbows back and up — imagine trying to put your elbows in your back pockets.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=chest+supported+row+form+tutorial",
    },
    {
      id: "3day-friday-arnold-press",
      name: "Arnold Press",
      sets: 3,
      reps: "10",
      restSeconds: 60,
      muscleGroup: "Shoulders",
      instructions: [
        "Sit holding dumbbells in front of your shoulders, palms facing you (like the top of a curl).",
        "As you press the weights overhead, rotate your palms to face forward.",
        "Reverse the rotation as you lower back to the start.",
      ],
      tips: [
        "Move smoothly — the rotation should happen gradually through the full range of motion.",
        "This exercise hits all three heads of the deltoid thanks to the rotation.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=arnold+press+form+tutorial",
    },
    {
      id: "3day-friday-concentration-curl",
      name: "Concentration Curl",
      sets: 3,
      reps: "10",
      restSeconds: 45,
      muscleGroup: "Biceps",
      instructions: [
        "Sit on a bench, lean forward slightly, and brace your working arm's elbow against your inner thigh.",
        "Curl the dumbbell up toward your shoulder, focusing on squeezing the bicep at the top.",
        "Lower slowly and repeat before switching arms.",
      ],
      tips: [
        "The braced position eliminates momentum, making this one of the best bicep isolation exercises.",
        "Go lighter than usual — you'll feel it more with strict form.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=concentration+curl+form+tutorial",
    },
    {
      id: "3day-friday-skull-crushers",
      name: "Skull Crushers (light)",
      sets: 3,
      reps: "12",
      restSeconds: 45,
      muscleGroup: "Triceps",
      instructions: [
        "Lie on a bench or the floor holding light dumbbells above your chest, arms extended.",
        "Bend your elbows to lower the dumbbells toward the sides of your head, keeping your upper arms vertical.",
        "Extend your elbows to press back to the start.",
      ],
      tips: [
        "Use light weight — poor form on this exercise can strain the elbows.",
        "Keep your upper arms still and only move your forearms.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=skull+crushers+dumbbell+form+tutorial",
    },
    {
      id: "3day-friday-side-plank",
      name: "Side Plank",
      sets: 3,
      reps: "20 sec each",
      restSeconds: 45,
      muscleGroup: "Core",
      instructions: [
        "Lie on your side with your elbow directly under your shoulder and feet stacked.",
        "Lift your hips off the floor to create a straight line from head to feet.",
        "Hold for 20 seconds, then switch sides.",
      ],
      tips: [
        "Don't let your hips sag — keep squeezing your obliques throughout.",
        "For a modification, bend your bottom knee to the floor for extra support.",
      ],
      youtubeUrl: "https://www.youtube.com/results?search_query=side+plank+form+tutorial",
    },
  ],
}

export const program3Day: WorkoutProgram = {
  id: "3day",
  name: "3-Day Full Body",
  days: [
    monday,
    restDay("3day-tuesday", "Tuesday", 2),
    wednesday,
    restDay("3day-thursday", "Thursday", 4),
    friday,
    restDay("3day-saturday", "Saturday", 6),
    restDay("3day-sunday", "Sunday", 0),
  ],
}
